#name = input("Введите ваше имя: ")
#current_year = 2024
#date_of_birth = int(input("В каком году вы родились? "))
#age = current_year - int(date_of_birth)
#print("Здравствуйте,", name)
#print("В этом году Вам", age, "год")
#print("привет, я строка в нижнем регистре")
my_string = input("Введите строку: ")
count_characters = len(my_string)
print(f"Количество символов: {count_characters}")
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])